apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: ingestor-app
  name: ingestor-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ingestor-app
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/mern-app: "true"
        io.kompose.service: ingestor-app
    spec:
      containers:
        - image: ingestor-app
          name: data-ingestor
          ports:
            - containerPort: 5678
          resources: {}
      hostname: data-ingestor
      restartPolicy: Always
status: {}
