apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: node-app
  name: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: node-app
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/mern-app: "true"
        io.kompose.service: node-app
    spec:
      containers:
        - env:
            - name: DATABASE
              valueFrom:
                configMapKeyRef:
                  key: DATABASE
                  name: Auth--env
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  key: PORT
                  name: Auth--env
          image: node-app
          name: node-app
          ports:
            - containerPort: 8000
          resources: {}
          volumeMounts:
            - mountPath: /usr/src/app
              name: node-app-claim0
            - mountPath: /usr/src/app/node_modules
              name: node-app-claim1
      restartPolicy: Always
      volumes:
        - name: node-app-claim0
          persistentVolumeClaim:
            claimName: node-app-claim0
        - name: node-app-claim1
          persistentVolumeClaim:
            claimName: node-app-claim1
status: {}
